sudo: false
language: rust
matrix:
  include:
    - name: "native"
      rust: stable
      env: TARGET_WASM=0
    - name: "wasm"
      rust: nightly
      env: TARGET_WASM=1
script:
  - ./ci/build.sh
