[package]
name    = "kiss3d"
version = "0.20.1"
authors = [ "Sébastien Crozet <developer@crozet.re>" ]

description = "3D graphics engine for Rust."
repository = "https://github.com/sebcrozet/kiss3d"
readme = "README.md"
keywords = [ "3D", "graphics", "OpenGL", "KISS" ]
license = "BSD-3-Clause"
autoexamples = true

include = [
    "src/**/*.rs",
    "src/text/*.ttf",
    "examples/**/*.rs",
    "examples/media",
    "examples/Cargo.toml",
    "Cargo.toml",
    "LICENSE",
    "Readme.md"
]

[lib]
name = "kiss3d"
path = "src/lib.rs"

[features]
conrod = [ "kiss3d_conrod" ]


[dependencies]
libc         = "0.2"
bitflags     = "1.0"
num-traits   = "0.2"
nalgebra     = "0.18"
ncollide3d   = "0.19"
image        = "0.21"
serde        = "1.0"
serde_derive = "1.0"
rusttype     = { version = "0.7", features = [ "gpu_cache" ] }
instant      = { version = "0.1", features = [ "stdweb" ]}
kiss3d_conrod = { version = "0.63", features = [ "stdweb" ], optional = true }

[target.'cfg(not(any(target_arch = "wasm32", target_arch = "asmjs")))'.dependencies]
gl = "0.11"
glutin = "0.19"

# We repeat all three targets instead of any(target_arch = "wasm32", target_arch = "asmjs")
# to avoid https://github.com/koute/stdweb/issues/135
[target.wasm32-unknown-unknown.dependencies]
stdweb = "0.4"
stdweb-derive = "0.5"

[target.wasm32-unknown-emscripten.dependencies]
stdweb = "0.4"
stdweb-derive = "0.5"

[target.asmjs-unknown-emscripten.dependencies]
stdweb = "0.4"
stdweb-derive = "0.5"

[dev-dependencies]
rand = "0.6"
ncollide2d = "0.19"